name: segmentio
package:
  name: Segment.IO
  description: SegmentIO Integration for Joomla
  update_site: http://updates.mrzen.com/segmentio
  version: 3.2
  author: Mr. Zen Ltd

contents:
  plugins:
    system:
      - segmentio
    content:
      - segmentio
    user:
      - segmentio
  libraries:
    - segmentio
